// CDN fallback map — permanent fal.media URLs for every runtime image the
// game loads. Used when the local path 404s (the Netlify upload proxy drops
// binary files); fal serves with `access-control-allow-origin: *`, so frames
// stay readable for the canvas keying passes.
export const CDN_MAP = {
  'assets/runtime/arena-blood-moon.webp': 'https://v3b.fal.media/files/b/0aa6c35e/pByv9Pj26olIIvTP-C9Mf_arena-blood-moon.webp',
  'assets/runtime/dual-art0.webp': 'https://v3b.fal.media/files/b/0aa6c360/bZzcDQIuNH9Q8crutdyJO_dual-art0.webp',
  'assets/runtime/dual-art1.webp': 'https://v3b.fal.media/files/b/0aa6c374/YdCntCl18mWs6XU_CJq6j_dual-art1.webp',
  'assets/runtime/dual-art2.webp': 'https://v3b.fal.media/files/b/0aa6c361/GjLIY4nARWT1jP4J_uiQA_dual-art2.webp',
  'assets/runtime/dual-art3.webp': 'https://v3b.fal.media/files/b/0aa6c361/7TuYHvv6kGmz3tcZ1T1ja_dual-art3.webp',
  'assets/runtime/dual-idle.webp': 'https://v3b.fal.media/files/b/0aa6c360/FYWzDnlHqVzARey-1RysK_dual-idle.webp',
  'assets/runtime/dual-run.webp': 'https://v3b.fal.media/files/b/0aa6c360/edl1LK7DDfFql0ita8yYH_dual-run.webp',
  'assets/runtime/oni-poses.webp': 'https://v3b.fal.media/files/b/0aa6c3b7/26PFmHaEU2qUU9XGoVG4j_oni-poses-dark.webp',
  'assets/runtime/player-hurt-anim.webp': 'https://v3b.fal.media/files/b/0aa6c35f/V4DNHIUGQGjIeeA_SXPi8_player-hurt-anim.webp',
  'assets/runtime/player-jump-anim.webp': 'https://v3b.fal.media/files/b/0aa6c35f/zdyD65JeFhehKHjpBvsQn_player-jump-anim.webp',
  'assets/runtime/player-special.webp': 'https://v3b.fal.media/files/b/0aa6c373/PTj44HvVH2av5duiHgE1M_player-special.webp',
  'assets/runtime/rite-sign.webp': 'https://v3b.fal.media/files/b/0aa6c361/wYI53IWDCq6vEP237G-W9_rite-sign.webp',
  'assets/runtime/ronin-idle.webp': 'https://v3b.fal.media/files/b/0aa6c371/Z-3DE1ul2Phtvn6f0mOGw_ronin-idle.webp',
  'assets/runtime/ronin-run-v2.webp': 'https://v3b.fal.media/files/b/0aa6c35e/5lBjJmh77NbbfYn9ORo9O_ronin-run-v2.webp',
  'assets/runtime/ronin-slash-v2.webp': 'https://v3b.fal.media/files/b/0aa6c35e/ITHW_VcRLG3iPv9YZUjob_ronin-slash-v2.webp',
  'assets/runtime/rival-idle.webp': 'https://v3b.fal.media/files/b/0aa6c4a3/DzpE6TaRuqU3RAvrsEEZu_rival-idle.webp',
  'assets/runtime/rival-run.webp': 'https://v3b.fal.media/files/b/0aa6c491/XNfBfGTum5K6-IpXo-JZo_rival-run.webp',
  'assets/runtime/rival-atk0.webp': 'https://v3b.fal.media/files/b/0aa6c4a5/r1mXUz0Sb71U6etA8KzT-_rival-atk0.webp',
  'assets/runtime/rival-atk1.webp': 'https://v3b.fal.media/files/b/0aa6c492/IfTFfkVXihahHHC2Y7Q-M_rival-atk1.webp',
  'assets/runtime/rival-atk2.webp': 'https://v3b.fal.media/files/b/0aa6c4a6/y1iDstR0RQJjye4yfxT_4_rival-atk2.webp',
  'assets/runtime/rival-hurt.webp': 'https://v3b.fal.media/files/b/0aa6c4a7/PCubTvn6jytpqFwUZ7Tfh_rival-hurt.webp',
  // arcade forge + adventure layers (host drops assets/** — these are the prod copies)
  'assets/base-f-outfit1.webp': 'https://v3b.fal.media/files/b/0aa70470/f2Ljow2ISMk898siwll0o_arc-base-f-outfit1.webp',
  'assets/base-m-outfit1.webp': 'https://v3b.fal.media/files/b/0aa70470/Bys1vx4PQ-_QlPd2wYXKb_arc-base-m-outfit1.webp',
  'assets/f-hair1.webp': 'https://v3b.fal.media/files/b/0aa70484/br5oa1--WkfwPAxnEUnGd_arc-f-hair1.webp',
  'assets/f-hair2.webp': 'https://v3b.fal.media/files/b/0aa70484/HebP8NtDRQPu75aePr0Ig_arc-f-hair2.webp',
  'assets/f-hair3.webp': 'https://v3b.fal.media/files/b/0aa70470/sEaYMiFE0RkxvMpYFQyaK_arc-f-hair3.webp',
  'assets/f-hair4.webp': 'https://v3b.fal.media/files/b/0aa70470/0qULRqbkkr1J_gny0fHxe_arc-f-hair4.webp',
  'assets/f-hair5.webp': 'https://v3b.fal.media/files/b/0aa70484/rW1pA2QwZInM03bqUj1gC_arc-f-hair5.webp',
  'assets/f-hat1.webp': 'https://v3b.fal.media/files/b/0aa70470/_PR6o2e5MgwxsD9D3ttYV_arc-f-hat1.webp',
  'assets/f-hat2.webp': 'https://v3b.fal.media/files/b/0aa70471/xPwMJB9USVtoGbPkhCHRT_arc-f-hat2.webp',
  'assets/f-hat3.webp': 'https://v3b.fal.media/files/b/0aa70484/BFgma-wx3zTGKWAE2wUjo_arc-f-hat3.webp',
  'assets/f-mask1.webp': 'https://v3b.fal.media/files/b/0aa70484/rT2qvLv6844x_LVA0cJyQ_arc-f-mask1.webp',
  'assets/f-mask2.webp': 'https://v3b.fal.media/files/b/0aa70471/CJ2BqPPBq-KL4FZ9WtyoK_arc-f-mask2.webp',
  'assets/f-outfit2.webp': 'https://v3b.fal.media/files/b/0aa70484/CdPdV8ZOsDhffoGBsBPJY_arc-f-outfit2.webp',
  'assets/f-outfit3.webp': 'https://v3b.fal.media/files/b/0aa70471/Ou7I9F3C8_kca46B2S8O3_arc-f-outfit3.webp',
  'assets/m-hair1.webp': 'https://v3b.fal.media/files/b/0aa70471/TlnkbSGRac_CmijAtS6wH_arc-m-hair1.webp',
  'assets/m-hair2.webp': 'https://v3b.fal.media/files/b/0aa70485/N5_e7EX61qOEhRjWOyBr6_arc-m-hair2.webp',
  'assets/m-hair3.webp': 'https://v3b.fal.media/files/b/0aa70471/--HOleEbNVefeZKtdr4tu_arc-m-hair3.webp',
  'assets/m-hair4.webp': 'https://v3b.fal.media/files/b/0aa70471/ovhMxxlsbZamBT3RQB5Ca_arc-m-hair4.webp',
  'assets/m-hair5.webp': 'https://v3b.fal.media/files/b/0aa70485/jI1u2_KP9do2LpP8hVxJi_arc-m-hair5.webp',
  'assets/m-hat1.webp': 'https://v3b.fal.media/files/b/0aa70471/w7z7i0FJ69b0rGAS-eEYR_arc-m-hat1.webp',
  'assets/m-hat2.webp': 'https://v3b.fal.media/files/b/0aa70471/bRjqm9a1tlrQJPT9g_oj5_arc-m-hat2.webp',
  'assets/m-hat3.webp': 'https://v3b.fal.media/files/b/0aa70485/NPOoBh9XhWFYAKPhydrIK_arc-m-hat3.webp',
  'assets/m-mask1.webp': 'https://v3b.fal.media/files/b/0aa70471/xgLffJ3S1NZDakC_7LQdz_arc-m-mask1.webp',
  'assets/m-mask2.webp': 'https://v3b.fal.media/files/b/0aa70472/WLNlVRByJ53MosQXHXktJ_arc-m-mask2.webp',
  'assets/m-outfit2.webp': 'https://v3b.fal.media/files/b/0aa70485/OcOwvc8v7hmsiw2suIDMn_arc-m-outfit2.webp',
  'assets/m-outfit3.webp': 'https://v3b.fal.media/files/b/0aa70472/iP7xnly6IdxbfcunJbRBa_arc-m-outfit3.webp',
  'assets/hero-top.webp': 'https://v3b.fal.media/files/b/0aa70472/-KOsFYhFFnjSe1MnRlxKm_arc-hero-top.webp',
};
